Repository ibexa/documentation-user, pull requests merged in 2018-12, with the labels that each got.

#24 EZP-28036: Update theme color
  docs/css/custom.css
Labels: Needs DOC review

#25 Removed outdated line about paragraph field.
  docs/creating_content_advanced.md
Labels: Ready for MERGE

#23 [WIP] Update screenshots to 2.4
  docs/creating_content_basic.md
  docs/img/admin_panel_language.png
  docs/img/dragging_lp_block.png
  docs/img/elements_menu.png
  docs/img/filtered_search.png
  docs/img/online_editor_menu.png
  docs/img/online_editor_table.png
  docs/img/rich_text_block_elements.png
  docs/img/siteaccess_bar.png
  docs/img/top_bar.png
  docs/img/user_preferences.png
  docs/search.md
Labels: Work in progress

#26 Workflow
  docs/img/dashboard_review_queue.png
  docs/img/workflow_events_timeline.png
  docs/img/workflow_panel.png
  docs/publishing.md
Labels: Ready for MERGE
