Repository ibexa/documentation-user, pull requests merged in 2020-07, with the labels that each got.

#64 Search in trash
  docs/site_organization/organizing_the_content.md
Labels: Needs DOC review

#65 Save incomplete draft
  docs/creating_content_basic.md
  docs/faq.md
  docs/publishing/publishing.md
  docs/site_organization/working_with_page.md
Labels: Needs DEV review, Needs DOC review

#61 Organizing content topic update (wildcards)
  docs/site_organization/img/3_1_Link_manager_sm.png
  docs/site_organization/img/3_1_URL_Wildcards_sm.png
  docs/site_organization/img/3_1_wildcard_detail.png
  docs/site_organization/organizing_the_content.md
Labels: Needs DEV review

#67 Missing enterprise bracket
  docs/publishing/publishing.md
Labels: Ready for MERGE

#66 EZEE-3105 Version compare
  docs/publishing/img/compare_results_1_col.png
  docs/publishing/img/compare_results_2_col.png
  docs/publishing/img/compare_results_media.png
  docs/publishing/publishing.md
Labels: Ready for MERGE

#68 Site Factory screenshot update
  docs/site_organization/img/site_factory_icon.png
  docs/site_organization/img/site_factory_new_site_step_1.png
  docs/site_organization/img/site_factory_new_site_step_2.png
  docs/site_organization/img/site_factory_site_list.png
  docs/site_organization/site_factory.md
Labels: Ready for MERGE

#69 Screeenshot update 3.1
  docs/content_model.md
  docs/img/filtered_search.png
  docs/img/left_menu_browse.png
  docs/img/left_menu_tree.png
  docs/img/login_form.png
  docs/img/plus_button.png
  docs/img/siteaccess_bar.png
  docs/img/top_bar.png
  docs/img/user_preferences.png
  docs/publishing/img/compare_icon_2.png
  docs/publishing/img/content_item_versions.png
  docs/publishing/img/drafts_admin_user.png
  docs/publishing/img/drafts_my_dashboard.png
  docs/publishing/img/reschedule_cancel_dashboard.png
  docs/publishing/img/workflow_panel.png
  docs/site_organization/img/3_1_Link_manager_sm.png
  docs/site_organization/img/Link_manager_sm.png
  docs/site_organization/img/URL_Wildcards_sm.png
  docs/site_organization/img/URL_wildcard_detail.png
  docs/site_organization/img/editing_page.png
  docs/site_organization/img/multi_file_move.png
  docs/site_organization/organizing_the_content.md
Labels: Ready for MERGE
