Repository ibexa/documentation-user, pull requests merged in 2022-12, with the labels that each got.

#167 Corporate Portal screenshot update for 4.3
  docs/shop_administration/img/cp_companies_section_back_office.png
  docs/shop_administration/img/cp_company_profile_back_office.png
  docs/shop_administration/img/cp_invitations_back_office.png
Labels: Ready for MERGE

#173 IBX-3373: Automatic assignment of asset collections
  docs/pim/work_with_product_assets.md
Labels: Ready for MERGE

#171 Screenshots update in User Documentation
  docs/content_management/content_organization/img/empty_trash_warning.png
  docs/content_management/content_organization/img/multi_file_delete.png
  docs/content_management/content_organization/img/multi_file_move.png
  docs/content_management/create_edit_content_items.md
  docs/content_management/create_edit_pages.md
  docs/content_management/img/add_field.png
  docs/content_management/img/content_types.png
  docs/content_management/img/rich_text_block_elements.png
  docs/content_management/img/select_page_blocks.png
  docs/content_management/img/select_start_location.png
  docs/content_management/taxonomy/img/taxonomy_content_list.png
  docs/content_management/taxonomy/img/taxonomy_delete_tag.png
  docs/content_management/taxonomy/work_with_tags.md
  docs/content_management/work_with_content_types.md
  docs/getting_started/img/udw.png
  docs/personalization/img/categorypath_filter.png
  docs/personalization/img/dashboard_models.png
  docs/personalization/img/models_time_period.png
  docs/personalization/img/scenario_configuration_strategy.png
  docs/personalization/img/scenario_filters.png
  docs/pim/img/catalogs_filters.png
  docs/pim/img/catalogs_product_list.png
  docs/pim/img/product_variants_generate.png
  docs/search/img/filtered_search.png
  docs/shop_administration/img/cp_create_company_back_office.png
  docs/shop_administration/img/enable_currency.png
  docs/shop_administration/img/order_management1.png
  docs/shop_administration/img/shipping_costs.png
Labels: Needs DOC review

#172 Add Connect documentation to doc switcher
  mkdocs.yml
Labels: Ready for MERGE

#174 Add inline image styling
  docs/css/custom.css
Labels: Ready for MERGE

#175 Perso user doc restructured
  docs/personalization/configure_models.md
  docs/personalization/configure_personalization.md
  docs/personalization/configure_scenarios.md
  docs/personalization/content_import.md
  docs/personalization/content_types.md
  docs/personalization/cross_content_type_reco.md
  docs/personalization/event_types.md
  docs/personalization/filters.md
  docs/personalization/integrate_scenario_results.md
  docs/personalization/personalization.md
  docs/personalization/recommendation_models.md
  docs/personalization/review_perso_performance.md
  docs/personalization/scenarios.md
  docs/personalization/use_cases.md
  mkdocs.yml
Labels: Work in progress

#166 IBX 4348: "Create Product" article added in User Documentation
  docs/persona_paths/manage_products.md
  docs/pim/create_edit_product.md
  docs/pim/img/create_new_product.png
  docs/pim/img/create_product.png
  docs/pim/img/edit_product.png
  docs/pim/products.md
  mkdocs.yml
Labels: Needs DOC review
