Repository ibexa/documentation-user, pull requests merged in 2023-06, with the labels that each got.

#202 Fix workflow deprecation warnings
  .github/workflows/build.yaml
Labels: Ready for MERGE

#206 Reorganize user paths
  docs/content_management/workflow_management/editorial_workflow.md
  docs/content_management/workflow_management/view_workflow_list.md
  docs/index.md
  docs/persona_paths/administrator.md
  docs/persona_paths/manage_content_model.md
  docs/persona_paths/manage_products.md
  docs/persona_paths/shop_manager.md
  docs/pim/create_edit_product.md
  docs/pim/manage_availability_and_stock.md
  docs/pim/manage_prices.md
  docs/pim/manage_prices_and_stock.md
  docs/pim/products.md
  mkdocs.yml
  plugins.yml
Labels: Needs DEV review

#201 IBX-5797: Ibexa Content to Ibexa Headless
  mkdocs.yml
Labels: Ready for MERGE

#207 4.5 screenshot update
  docs/commerce/img/create_new_payment_method.png
  docs/commerce/img/free_shipping.png
  docs/commerce/img/order_list.png
  docs/commerce/img/payment_list.png
  docs/content_management/content_organization/classify_content.md
  docs/content_management/content_organization/img/multi_file_move.png
  docs/content_management/content_organization/img/sections.png
  docs/content_management/img/calendar_widget.png
  docs/content_management/img/calendar_widget_toggler_cal_list.png
  docs/content_management/img/content_types.png
  docs/content_management/img/select_page_blocks.png
  docs/customer_management/img/cp_applications_list.png
  docs/getting_started/img/left_menu_tree.png
  docs/getting_started/img/login_form.png
  docs/getting_started/img/top_bar.png
  docs/getting_started/img/user_preferences.png
  docs/personalization/configure_models.md
  docs/personalization/img/categorypath_filter.png
  docs/personalization/img/models_edit.png
  docs/personalization/img/scenario_filters.png
  docs/pim/img/enable_currency.png
  docs/pim/img/product_price.png
  docs/pim/img/product_variants_delete.png
  docs/pim/img/setting_product_price.png
  docs/website_organization/img/site_factory_site_list.png
Labels: Needs DOC review
